--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5 (Homebrew)
-- Dumped by pg_dump version 14.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ielts_schema; Type: SCHEMA; Schema: -; Owner: ielts_user
--

CREATE SCHEMA ielts_schema;


ALTER SCHEMA ielts_schema OWNER TO ielts_user;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: long_term_memory; Type: TABLE; Schema: ielts_schema; Owner: ielts_user
--

CREATE TABLE ielts_schema.long_term_memory (
    "sessionId" integer NOT NULL,
    "userId" integer,
    "timestamp" timestamp with time zone,
    topic character varying,
    performance integer
);


ALTER TABLE ielts_schema.long_term_memory OWNER TO ielts_user;

--
-- Name: short_term_memory; Type: TABLE; Schema: ielts_schema; Owner: ielts_user
--

CREATE TABLE ielts_schema.short_term_memory (
    "sessionId" integer NOT NULL,
    "userId" integer,
    "userInput" character varying,
    "currentTopics" character varying[],
    fluency integer,
    "otherMetricsOfEvaluation" integer[],
    "longAnswerCount" integer,
    "shortAnswerCount" integer,
    "topicsToPracticeLater" character varying[]
);


ALTER TABLE ielts_schema.short_term_memory OWNER TO ielts_user;

--
-- Data for Name: long_term_memory; Type: TABLE DATA; Schema: ielts_schema; Owner: ielts_user
--

COPY ielts_schema.long_term_memory ("sessionId", "userId", "timestamp", topic, performance) FROM stdin;
\.


--
-- Data for Name: short_term_memory; Type: TABLE DATA; Schema: ielts_schema; Owner: ielts_user
--

COPY ielts_schema.short_term_memory ("sessionId", "userId", "userInput", "currentTopics", fluency, "otherMetricsOfEvaluation", "longAnswerCount", "shortAnswerCount", "topicsToPracticeLater") FROM stdin;
\.


--
-- Name: long_term_memory long_term_memory_pkey; Type: CONSTRAINT; Schema: ielts_schema; Owner: ielts_user
--

ALTER TABLE ONLY ielts_schema.long_term_memory
    ADD CONSTRAINT long_term_memory_pkey PRIMARY KEY ("sessionId");


--
-- Name: short_term_memory short_term_memory_pkey; Type: CONSTRAINT; Schema: ielts_schema; Owner: ielts_user
--

ALTER TABLE ONLY ielts_schema.short_term_memory
    ADD CONSTRAINT short_term_memory_pkey PRIMARY KEY ("sessionId");


--
-- PostgreSQL database dump complete
--

